title: AI Capriccio
description: Experiments, thoughts, and engineering notes in the AI era

theme: just-the-docs

url: https://fanqi1909.github.io
baseurl: /ai-capriccio

search_enabled: true
heading_anchors: true

aux_links:
  GitHub:
    - https://github.com/fanqi1909/ai-capriccio
